name: cleopatra
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
 
  equatable: ^2.0.5
  
  dartz: ^0.10.1
 
  dio: ^5.4.0
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.4
  flutter_localizations:
    sdk: flutter
 
  firebase_storage: ^12.4.2
  cloud_firestore: ^5.6.3
  badges: ^3.1.2
  excel: ^4.0.3
  share_plus: ^10.1.4
  avatar_glow: ^3.0.1
  bitsdojo_window: ^0.1.6
  device_screen_size: ^0.0.2



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  firebase_core: ^3.11.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  path_provider: ^2.1.3
  open_file: ^3.3.2
  shared_preferences: ^2.2.3
  download: ^1.0.0
  firebase_messaging: ^15.2.2
  http: ^1.2.1
  pdf: ^3.11.0
  firebase_auth: ^5.4.2
  circular_menu: ^4.0.0
  onesignal_flutter: ^5.3.0
  syncfusion_flutter_charts: ^28.2.4+1
  time_picker_spinner_pop_up: ^2.0.0
  intl: ^0.19.0
  mat_month_picker_dialog: ^1.1.2
  get: ^4.6.6
  dropdown_search: ^5.0.6
  encrypt: ^5.0.3
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  pie_chart: ^5.4.0
  animated_text_kit: ^4.2.3
  flutter_zoom_drawer: ^3.2.0
  carousel_slider: ^5.0.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.4.0
  easy_localization: ^3.0.7+1
  smooth_page_indicator: ^1.2.0+3
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.10
  flutter_slidable: ^4.0.0  
  animated_analog_clock: ^0.2.2
  qr_code_scanner_plus: ^2.0.14
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: hsn 
      fonts:
        - asset: assets/fonts/hsn.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

